### ISSUE TITLE
Error: Problem with the CMake installation, aborting build. CMake executable is cmake

### ISSUE THREAD

**Issue by aknahin** [dmpelt/foam_ct_phantom#10]
A error is showing while I am running this command `python setup.py install`

Full error code:
```
C:\Users\Lenovo\anaconda3\Lib\site-packages\setuptools\_distutils\cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
Traceback (most recent call last):
  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\skbuild\setuptools_wrap.py", line 645, in setup
    cmkr = cmaker.CMaker(cmake_executable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\skbuild\cmaker.py", line 148, in __init__
    self.cmake_version = get_cmake_version(self.cmake_executable)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lenovo\anaconda3\Lib\site-packages\skbuild\cmaker.py", line 105, in get_cmake_version
    raise SKBuildError(msg) from err

Problem with the CMake installation, aborting build. CMake executable is cmake
```

**Comment by dmpelt** [comment]
I see you are using anaconda! Is there a reason for not using the package from conda-forge? You should be able to install this with the ```conda install -c conda-forge foam_ct_phantom``` command.
